module.exports = {
  "aa" :"ꜳ",
  "ae" :"æ",
  "av" :"ꜹ",
  "oe" :"œ",
  "ue" :"ᵫ",
  "ff" :"ﬀ",
  "fl" :"ﬂ",
  "fi" :"ﬁ",
  "ffi" :"ﬃ",
  "ffl" :"ﬄ",
  "oo" :"ꝏ",
  "ft" :"ﬅ",
  "fs" :"ß",
  "fz" :"ß",
  "et" :"&",
  "st" :"ﬆ",
  "db" :"ȸ",
  "dz" :"ʣ",
  "ij" :"ĳ",
  "ls" :"ʪ",
  "lz" :"ʫ",
  "qp" :"ȹ",
  "ts" :"ʦ",
  "tf" :"ʧ",
  "?!" :"‽",
  "!?" :"‽",
  "about": "~",
  "because": "B/C",
  "thanks": "THX",
  "great": "GR8",
  "later": "L8R",
  "wait": "W8",
  "your": "UR",
  "cutie": "QT",
  "today": "2DAY",
  "tonight": "2nite",
  "night": "nite",
  "light": "lite",
  "for": "4",
  "address": "ADR",
  "before": "B4",
  "toilet": "WC",
  "bathroom": "WC",
  "see": "C",
  "date": "D8",
  "definitely": "DEF",
  "doing": "doin",
  "easy": "EZ",
  "favourite": "FAV",
  "favorite": "FAV",
  "forward": "FWD",
  "hate": "H8",
  "jelious": "JELLY",
  "okay ok": "K",
  "later": "L8R",
  "minutes": "MINS",
  "enough": "NUFF",
  "pizza": "'ZA",
  "please": "PLZ",
  "computer windows": "PC",
  "windows": "PC",
  "password": "PW",
  "are": "r",
  "sorry": "sry",
  "seriously": "srsly",
  "straight": "STR8",
  "sucks": "sux",
  "text": "TXT",
  "twitter": "TWTR",
  "you": "u",
  "yours": "urs",
  "without": "w/o",
  "wait": "W8",
  "at": "@"
}

  // "with": "w/",
  // . A => .A

